### ISSUE TITLE
deadlock when using RemoteFile.WriteTo or ReadFrom

### ISSUE THREAD

**Issue by jannson** [hirochachacha/go-smb2#12]
lock here:
https://github.com/hirochachacha/go-smb2/blob/master/client.go#L1316

and lock again:
https://github.com/hirochachacha/go-smb2/blob/master/client.go#L1148

which cause deadlock.

**Comment by hirochachacha** [comment]
Thank you for great suggestions :)
I hope it's ok now.

**Comment by jannson** [comment]
It works, Thank you!
