### ISSUE TITLE
Question about RemoteFile.copyTo implement

### ISSUE THREAD

**Issue by jannson** [hirochachacha/go-smb2#13]
I wrote a simple test for RemoteFile.copyTo with server side copy implement, It works.

But I double about  it implements:

1.  

The "f" is lock outside , but the "wf" is not lock, here change the offset of "wf"
https://github.com/hirochachacha/go-smb2/blob/d9687bf46c8755b29966c7287aae01925eab1d93/client.go#L1195

2. 

Again the "f" is already locked, may cause deadlock in copyBuffer (I cannot test since my simple test code not reach here) 

https://github.com/hirochachacha/go-smb2/blob/d9687bf46c8755b29966c7287aae01925eab1d93/client.go#L1286

**Comment by hirochachacha** [comment]
Thanks again!
