### ISSUE TITLE
Better error for misleading path separator (\ vs /)

### ISSUE THREAD

**Issue by dragoscirjan** [hirochachacha/go-smb2#14]
Hi,

I spent about half a day trying to debug this.

```go
	testDirPath := fmt.Sprintf("testDir%d/testDir%d", rand.Int(), rand.Int())

	// fs.RemoveAll(testDir)

	err = fs.MkdirAll(testDirPath, 0755)
	t.Logf("%s", err)
	if err != nil {
		t.Fatal(err)
	}
	// defer fs.RemoveAll(testDirPath)
```
Please notice the `/` instead of `\` from the path.

Now... I do understand it is partially my fault for not understanding the SMB/Windows documentation better, however... **"invalid argument"** is not the best error to be thrown.

This is a very easy and common mistake someone could do, especially when working on multiple OS platforms. Maybe it would deserve a better error?

Thanks in advance!

**Comment by hirochachacha** [comment]
Fair enough. Thank you.
