### ISSUE TITLE
Finding out shared location disk free info

### ISSUE THREAD

**Issue by dragoscirjan** [hirochachacha/go-smb2#15]
Hi again,

This is not an issue, more of a question. Asking here because I have no other place to ask:

Any idea how I could achieve this: https://gist.github.com/lunny/9828326 on a shared smb location?

**Comment by hirochachacha** [comment]
I didn't implement it, but https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/5b9ebada-9992-45ea-8413-164188bf28a6 is maybe what you're looking for.
