### ISSUE TITLE
Write fails with `connection error: EOF` when source file is large

### ISSUE THREAD

**Issue by lucastheisen** [hirochachacha/go-smb2#16]
I was unable to determine the exact point at which it starts failing, but if my test file (generated [lorem ipsum](https://lipsum.com/) text) is 15MB it fails with `connection error: EOF` (a similarly generated text file of 7MB works just fine).

My code is really simple just:

```go
var dest = "OMITTED_IP_ADDRESS"
var port = 1445
var domain = "OMITTED"
var username = "OMITTED"
var password = "OMITTED"
var share = "OMITTED"
var filePath = "C:/Temp/shares/up/test.txt"

func main() {
	conn, err := net.Dial("tcp", fmt.Sprintf("%s:%d", dest, port))
	if err != nil {
		fmt.Printf("failed to net dial: %v", err)
		os.Exit(1)
	}
	defer conn.Close()

	d := &smb2.Dialer{
		Initiator: &smb2.NTLMInitiator{
			User:     username,
			Password: password,
			Domain:   domain,
		},
	}

	client, err := d.Dial(conn)
	if err != nil {
		fmt.Printf("failed to smb dial: %v", err)
		os.Exit(1)
	}
	defer client.Logoff()

	fs, err := client.Mount(fmt.Sprintf(`\\%s\%s`, dest, share))
	if err != nil {
		fmt.Printf("failed to mount: %v", err)
		os.Exit(1)
	}
	defer fs.Umount()

	dest, err := fs.Create("foo.txt")
	if err != nil {
		fmt.Printf("failed to create: %v", err)
		os.Exit(1)
	}
	defer dest.Close()

	src, err := os.Open(filePath)
	if err != nil {
		fmt.Printf("failed to open source: %v", err)
		os.Exit(1)
	}
	defer src.Close()

	bytesWritten, err := io.Copy(dest, src)
	if err != nil {
		fmt.Printf("failed to open source: %v", err)
		os.Exit(1)
	}
	defer src.Close()

	fmt.Printf("Successfully wrote %d bytes", bytesWritten)
}
```

When run this results in:

```text
failed to open source: write foo.txt: connection error: EOF
```

**Comment by hirochachacha** [comment]
I guess the server shutdown the connection. Unfortunately, current implementation doesn't support retrying connection flow described in https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/3309c3d1-3daf-4448-9faa-81d2d6aa3315

https://golang.org/pkg/net/#TCPConn.SetKeepAlivePeriod might solve your problem for now.

**Comment by lucastheisen** [comment]
@hirochachacha , I just tried modifying to set keep alive:
```go
	netDialer := net.Dialer{KeepAlive: time.Second}
	conn, err := netDialer.Dial("tcp", fmt.Sprintf("%s:%d", dest, port))
	if err != nil {
		fmt.Printf("failed to net dial: %v", err)
		os.Exit(1)
	}
	defer conn.Close()
```
It still fails for large files.  Some further testing showed that it is somewhere between 6-8MB where it starts to fail.

**Comment by lucastheisen** [comment]
A little more investigation makes me think it has to do with the implementation of the [`ReaderFrom`/`WriterTo`](https://github.com/hirochachacha/go-smb2/blob/master/client.go#L1296-L1338) interfaces (which are used by the `io.Copy` function).  When i switched from using `io.Copy` to an _exact_ copy of [the internal `copyBuffer` function](https://github.com/hirochachacha/go-smb2/blob/master/client.go#L1149-L1174) using a fixed buffer size of `64 * 1024` i stopped getting the EOF error, and the transfer completed as expected.

So, while its unfortunate to have to duplicate this code in my project, I have a workaround that gets me passed this issue.  Thanks for putting this project together!

**Comment by hirochachacha** [comment]
Hmm. I'll look into this. Thank you for the report.

**Comment by jannson** [comment]
A bug in copyBuffer implement: 

https://github.com/hirochachacha/go-smb2/issues/19

I try fix this bug, but there still something wrong in somewhere.

**Comment by jannson** [comment]
pr here: https://github.com/hirochachacha/go-smb2/pull/20

Please check if this bug is fix

**Comment by turbidwater** [comment]
We hit this issue as well. Would love for it to be fixed.

**Comment by hirochachacha** [comment]
I wish I could.
But I cannot reproduce the issue in my environment.
Probably, #39 is the same issue.
So I did 
```bash
#!/bin/bash

set -e

for i in `seq 1 100`
do
  dd if=/dev/urandom of=/tmp/test count=${i} bs=1M 2>/dev/null
  go run smb2read.go smb2://localhost/tmp/test >/dev/null
  echo test${i} succeeded 
done
```
on linux and macos. Unfortunately, I couldn't see anything interesting.

**Comment by jannson** [comment]
Where is the smb2read.go ?

You must call io.Copy (which call ReaderFrom/WriterTo interfaces) to reproduct this issue.

**Comment by hirochachacha** [comment]
I didn't remember exact source code, but I remember I used `io.Copy`.

**Comment by hirochachacha** [comment]
https://github.com/hirochachacha/go-smb2/blob/master/client.go#L1769-L1787

Current implementation use `maxReadSize` and `maxWriteSize` to define buffer size.
Those values are retrieved from the smb2 server. Maybe I'm not handling those values properly.

**Comment by hirochachacha** [comment]
Perhaps, window don't accept more than 65536 bytes read request even though they tell us maxReadSize > 65536.
I read some other project's source code and it seems that they have that assumption.

**Comment by hirochachacha** [comment]
Thank you. I hope it's fixed now.
