### ISSUE TITLE
List files in a directory

### ISSUE THREAD

**Issue by Pch12** [hirochachacha/go-smb2#17]
Hey, 
How can I list files in a directory with Readdir() if I have a share entered by a user?
What i'm really wondering and I have been trying to figure out how can I create a pointer for the type *RemoteFile in order to use other functions?

**Comment by hirochachacha** [comment]
Are you looking for https://godoc.org/github.com/hirochachacha/go-smb2#RemoteFileSystem.Open ?
```
conn, err := net.Dial("tcp", "localhost:445")
if err != nil {
    panic(err)
}
defer conn.Close()

d := &smb2.Dialer{
    Initiator: &smb2.NTLMInitiator{
        User:     "Guest",
        Password: "",
        Domain:   "MicrosoftAccount",
    },
}

c, err := d.Dial(conn)
if err != nil {
    panic(err)
}
defer c.Logoff()

fs, err := c.Mount(`\\localhost\share`)
if err != nil {
    panic(err)
}
defer fs.Umount()

dir, err := fs.Open(`mydir`)
 if err != nil {
    panic(err)
}
defer dir.Close()

fi, err := dir.Readdir(-1)
if err != nil {
    panic(err)
}
// do something
```

**Comment by Pch12** [comment]
Perfect thank you!

**Comment by Pch12** [comment]
how can you list all the shares available for just an input like \\192.168.1.29, because the mount() function will not accept it..

**Comment by hirochachacha** [comment]
To list all SMB share isn't part of the SMB protocol. 
I guess you need SRVS protocol https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/c4a98e7b-d416-439c-97bd-4d9f52f8ba52 which, unfortunately,  isn't supported in this library.

**Comment by Pch12** [comment]
Thanks alot,
Do you think this can be done from a linux OS though? running this dll and all
