### ISSUE TITLE
does mount point always have to be \\localhost\shared-folder ?

### ISSUE THREAD

**Issue by dragoscirjan** [hirochachacha/go-smb2#23]
Hi,

I've noticed smth in Windows. 
Even though shared locations are, let's say,` \\localhost\folder1`, `\\localhost\folder2`
I can also access `\\localhost` like this:

```
\\localhost
  |+ folder1
  |+ folder2
```

I am not familiar with SMB protocol that much, I'm just asking someone who knows better alerady.
Is there any way I can mount `\\localhost` instead of `\\localhost\share` ?

```go
fs, err := c.Mount(`\\localhost`)
if err != nil {
    panic(err)
}
```

**Comment by hirochachacha** [comment]
You can't mount `\\localhost` directly. However there is another protocol which allows to list SMB shares.  https://github.com/hirochachacha/go-smb2/issues/17#issuecomment-615582157
Although it's too complicated for me to start investigation.
