### ISSUE TITLE
Incomplete Hash Auth?

### ISSUE THREAD

**Issue by lukeasec** [hirochachacha/go-smb2#24]
Hey, awesome library! 

I was trying to use it for NTML auth with just the hash, and I noticed a potential issue with the implementation; in the `client.go` you are doing the following

https://github.com/hirochachacha/go-smb2/blob/823d9b85469032f3d87602519131acc14de0c91f/internal/ntlm/client.go#L185

but I believe that is wrong, because the hash that people usually get (by using online ntlm converter, from local SAM or other means), is just the MD4 value of the UTF16le value of the password. Therefore that hash needs to be computed with the username and the password, as you are doing here

https://github.com/hirochachacha/go-smb2/blob/823d9b85469032f3d87602519131acc14de0c91f/internal/ntlm/ntlm.go#L120-L128

essentially the hash that you usually get is the `key` value of line 124. One fix I guess could be calling in `client.go` another function like the following, when the hash is not `nil`:

```
func ntowfv2_hash(USER, hash, domain []byte) []byte {
	hm := hmac.New(md5.New, hash)
	hm.Write(USER)
	hm.Write(domain)
	return hm.Sum(nil)
}
```

**Comment by hirochachacha** [comment]
Nice find! Thank you.
