### ISSUE TITLE
Mac OS: invalid response error: asn1: structure error: superfluous leading zeros in length

### ISSUE THREAD

**Issue by kshetty1990** [hirochachacha/go-smb2#30]
Hi 

platform: macos

I am getting this error 

panic: invalid response error: asn1: structure error: superfluous leading zeros in length

code is pasted below 

I am interested in the filename.

**Comment by kshetty1990** [comment]
`package main
import (
	"fmt"
	"net"
	"github.com/hirochachacha/go-smb2"
)
func main() {
	conn, err := net.Dial("tcp", "<IP>:445")
	if err != nil {
		return
	}
	defer conn.Close()
	d := &smb2.Dialer{
		Initiator: &smb2.NTLMInitiator{
			User:     "<user>",
			Password: "<pwd>",
			Domain:   "<domain>",
		},
	}
	c, err := d.Dial(conn)
	if err != nil {
		panic(err)
	}
	defer c.Logoff()
	fs, err := c.Mount(`\\<IP>\<path>\<folder1>\<folder2>\<filename>`)
	if err != nil {
		panic(err) // panic here
	}
	fmt.Println(fs)
}`

**Comment by marklabenski** [comment]
I have the same problem, which seem to be a problem with Windows servers which have Signing enforced. I tried the same code on other hosts and it's working there. I switched from nodejs to python to golang to be able to upload files to that nasty mircosoft stuff for days now. All libraries got me different errors for this particular server :/

My code is nearly the same, so i'm not posting it here.

**Comment by dragoscirjan** [comment]
Hi guys,
I had the same problem with a different OS developed by NetApp, and their support was related with the fact that GoLang's ASN1 supports only DER encoding and they send auth responses using BER encoding. Please see Pull Request #34 and let me if it solves your problems.

**Comment by dragoscirjan** [comment]
Forgot to mention, the error I was getting, is the same.

**Comment by hirochachacha** [comment]
I couldn't reproduce the exact same error message, but I think following code is culprit.
```
	fs, err := c.Mount(`\\<IP>\<path>\<folder1>\<folder2>\<filename>`)
	if err != nil {
		panic(err) // panic here
	}
```
The mount path should be a valid UNC root path like `\\<server>\<share>`. You can't specify `<folder>` and `<filename>`

If that's not your case, please let me know, so I'll reopen this.
