### ISSUE TITLE
failed to open source: write test: connection error: EOFexit status 1

### ISSUE THREAD

**Issue by fdefilippo** [hirochachacha/go-smb2#39]
Hello, trying to copy a file larger than 8Mb I get the error:

$ dd if=/dev/zero of=/tmp/test count=7 bs=1M
$ go run bugsmb.go
Successfully wrote 7340032 bytes
$ dd if=/dev/zero of=/tmp/test count=8 bs=1M
$ go run bugsmb.go
failed to open source: write test: connection error: EOFexit status 1

It seems to me that the problem has already been reported:

https://github.com/hirochachacha/go-smb2/pull/20

but apparently the fix does not work.

**Comment by fdefilippo** [comment]
Hi, changing the buffer in the clients.go file at line 1564: 

```
func copyBuffer(r io.Reader, w io.Writer, buf []byte) (n int64, err error) {
  for {
    nr, er := r.Read(buf[:1024*1024*7])
```

it works properly.

**Comment by hirochachacha** [comment]
done.
