### ISSUE TITLE
ListSharenames results in fatal error if response is larger than 4280 bytes

### ISSUE THREAD

**Issue by TheskerAndre** [hirochachacha/go-smb2#41]
Scenario:

- Create about 25 Shares for a host
- Try to call ListSharenames() to list the shares
=> panic(), because of "slice bounds out of range [:4284] with capacity 4280" exception

![hirochacha_exception](https://user-images.githubusercontent.com/26229789/108385469-fd037100-720b-11eb-8c5a-797b1bee23fe.png)

I think the answer is to big for one ioctl response. So bevore we read the shares we have to call all fragments.
I tried to increase the MaxOutputResponse and the max xmit frag and max recv frag but without success.

Can you help me to fix the problem?

**Comment by hirochachacha** [comment]
Thanks for the report.
