### ISSUE TITLE
authentication fail using local domain user to trusted domain computer

### ISSUE THREAD

**Issue by fdefilippo** [hirochachacha/go-smb2#45]
Hi, the context is the same as issue #40 the question is different: trying to connect to a share of a trusted domain using a user of the local domain, during the session setup the library uses the remote domain instead of the one passed to it:

Session Setup Request, NTLMSSP_NEGOTIATE
Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE
Session Setup Request, NTLMSSP_AUTH, User: **REMOTE_DOMAIN**\USER-LOCAL-DOMAIN
Session Setup Response, Error: STATUS_LOGON_FAILURE

**Comment by hirochachacha** [comment]
Could you show me the code? I couldn't understand how you specify the domain. Perhaps following line might help?
https://github.com/hirochachacha/go-smb2/blob/master/internal/ntlm/client.go#L137-L139

**Comment by fdefilippo** [comment]
I'm sorry it was my mistake, sorry if I wasted your time I'm sorry.

**Comment by hirochachacha** [comment]
No worries. Thanks for the report!
