### ISSUE TITLE
Connecting directly to a specific path/folder

### ISSUE THREAD

**Issue by korniii** [hirochachacha/go-smb2#59]
I currently have the issue that I want to connect directly to a path/folder. Connecting to the server and then finding the folder seems to be no option since i have only access to the specific path. (e.g. \\\\something.test.com\specific_path$)

This works when connecting from desktop.

However I don't know how to add this path to the connection string and therefore always get:

panic: response error: The attempted logon is invalid. This is either due to a bad username or authentication information.

Is there a way to add this path to the connection string? Thanks in advance.

Code snippet for clarification.

```
func main() {
	conn, err := net.Dial("tcp", "something.test.com:445")
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	d := &smb2.Dialer{
		Initiator: &smb2.NTLMInitiator{
			User:     "<USER>",
			Password: "<PASSWORD>",
		},
	}

	s, err := d.Dial(conn)
	if err != nil {
		panic(err)
	}
}
```

**Comment by jxsl13** [comment]
https://github.com/hirochachacha/go-smb2/blob/master/example_test.go

Isnt that the mount point?

**Comment by korniii** [comment]
I thought so too, but i‘m already thrown out on the dial in. That‘s why i thought there might be some kind of role based access and a direct way to address the mountpoint on dial in.

**Comment by hirochachacha** [comment]
As far as I can tell, smb2 server don't use mountpoint information for authentication. so, I think there're different reasons .
