### ISSUE TITLE
Process hangs in smb2 stack

### ISSUE THREAD

**Issue by testcheyi** [hirochachacha/go-smb2#9]
I am occasionally seeing our application hang in smb2 code. Can you let me know from this stack what could be going wrong.

Following is the stack that was observed.
SIGQUIT: quit
PC=0x7fff6dd92ce6 m=0 sigcode=0
 
goroutine 0 [idle]:
runtime.notetsleepg(0x46f6440, 0x65faf31, 0x0)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/lock_sema.go:280 +0x41 fp=0xc000041760 sp=0xc000041720 pc=0x400c6e1
runtime.timerproc(0x46f6420)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/time.go:311 +0x2ea fp=0xc0000417d8 sp=0xc000041760 pc=0x404de9a
runtime.goexit()
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000417e0 sp=0xc0000417d8 pc=0x405d5b1
created by runtime.(*timersBucket).addtimerLocked
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/time.go:169 +0x10e
 
goroutine 51 [syscall]:
runtime.notetsleepg(0x46f6440, 0x65faf31, 0x0)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/lock_sema.go:280 +0x41 fp=0xc000041760 sp=0xc000041720 pc=0x400c6e1
runtime.timerproc(0x46f6420)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/time.go:311 +0x2ea fp=0xc0000417d8 sp=0xc000041760 pc=0x404de9a
runtime.goexit()
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000417e0 sp=0xc0000417d8 pc=0x405d5b1
created by runtime.(*timersBucket).addtimerLocked
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/time.go:169 +0x10e
 
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000234600, 0x43d85c8, 0x8, 0x4412aa8, 0x4078f01)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc000234200)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc000234200, 0xc000053e30)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/testing/testing.go:865 +0xc0
testing.runTests(0xc0000fec80, 0x46ec860, 0x8, 0x8, 0x0)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc00017a080, 0x0)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/testing/testing.go:1072 +0x162
main.main()
       _testmain.go:56 +0x13e
 
goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x46f2500)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/golang/glog/glog.go:915 +0x8b
created by github.com/golang/glog.init.0
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/golang/glog/glog.go:410 +0x272
 
goroutine 18 [sleep, 1 minutes]:
runtime.goparkunlock(...)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/proc.go:307
time.Sleep(0xdf8475800)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/time.go:105 +0x159
dg/machine_info.init.0.func1()
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/dg/machine_info/info.go:58 +0x30
created by dg/machine_info.init.0
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/dg/machine_info/info.go:56 +0x3a
 
goroutine 3263 [select]:
github.com/hirochachacha/go-smb2.(*conn).recv(0xc0004661a0, 0xc0004d6aa0, 0x30, 0x43a5060, 0x1, 0xc0001264e0, 0xc000345380)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/conn.go:472 +0xc7
github.com/hirochachacha/go-smb2.(*session).recv(0xc0003ea000, 0xc0004d6aa0, 0xb, 0x10, 0x447a300, 0xc0001264e0, 0x0)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/session.go:300 +0x45
github.com/hirochachacha/go-smb2.sessionSetup(0xc0004661a0, 0x447a2c0, 0xc0001721c0, 0xc000455740, 0xc0004661a0, 0x0)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/session.go:235 +0x593
github.com/hirochachacha/go-smb2.(*Dialer).Dial(0xc0000958f0, 0x447c940, 0xc000458008, 0x11, 0x6fc23ac00, 0x447c940)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/client.go:47 +0x15d
dg/smbfs.(*FileSystem).setupRFS(0xc0000f80f0, 0x0, 0x0, 0x43fd5ea, 0xd, 0x0, 0x0, 0x43db1fa, 0xa, 0x43fd5f8, ...)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/dg/smbfs/filesystem.go:180 +0x2ed
dg/smbfs.(*FileSystem).getRfs(0xc0000f80f0, 0x0, 0x0, 0xd, 0x43db205, 0x6)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/dg/smbfs/filesystem.go:133 +0x158
dg/smbfs.(*FileSystem).NewLocation(0xc0000f80f0, 0x0, 0x0, 0x43fd606, 0x39, 0x0, 0x0, 0x0, 0x0)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/dg/smbfs/filesystem.go:100 +0x95
dg/dgvfs.ConnectSmbfs(0x43db205, 0x6, 0x43d7d19, 0x6, 0x43fd5ea, 0xd, 0x43fd5f7, 0x48, 0x0, 0x0, ...)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/dg/dgvfs/vfs_smbfs.go:56 +0x587
decrypter.connect(0x43db1fa, 0x11, 0x43d7d19, 0x6, 0x43fd5e4, 0x5b, 0x0, 0x0, 0x0, 0x0)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/sputnik/src/decrypter/connect.go:18 +0x203
decrypter.List(0x4472e60, 0xc0003702a0, 0x43db1fa, 0x11, 0x43d7d19, 0x6, 0x43fd5e4, 0x5b, 0x1, 0x0, ...)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/sputnik/src/decrypter/list.go:29 +0x8f
decrypter.list(0xc000234600, 0xc000348360, 0x5c, 0x43d7401, 0xc000090950, 0x1, 0x1, 0xc00039bce0, 0x2, 0x2, ...)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/sputnik/src/decrypter/decrypter_test.go:42 +0xab
decrypter.TestList(0xc000234600)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/sputnik/src/decrypter/decrypter_test.go:81 +0x1ee
testing.tRunner(0xc000234600, 0x4412aa8)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/testing/testing.go:916 +0x35a
 
goroutine 3351 [select]:
github.com/hirochachacha/go-smb2.(*conn).runSender(0xc0004661a0)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/conn.go:487 +0x148
created by github.com/hirochachacha/go-smb2.(*Negotiator).negotiate
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/conn.go:98 +0x18f
 
goroutine 3352 [IO wait]:
internal/poll.runtime_pollWait(0x4f00ea8, 0x72, 0xffffffffffffffff)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00017a298, 0x72, 0x0, 0x4, 0xffffffffffffffff)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00017a280, 0xc00005ad84, 0x4, 0x4, 0x0, 0x0, 0x0)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/internal/poll/fd_unix.go:169 +0x1f2
net.(*netFD).Read(0xc00017a280, 0xc00005ad84, 0x4, 0x4, 0xc0003d6e08, 0x3, 0x0)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000458008, 0xc00005ad84, 0x4, 0x4, 0x0, 0x0, 0x0)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/net/net.go:177 +0x69
io.ReadAtLeast(0x4473480, 0xc000458008, 0xc00005ad84, 0x4, 0x4, 0x4, 0xc0001ef180, 0x131, 0x131)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/io/io.go:310 +0x88
io.ReadFull(...)
       /Users/usirsiwal/work/dg/sasource/go/mac/go/src/io/io.go:329
github.com/hirochachacha/go-smb2.(*directTCP).ReadSize(0xc00005ad80, 0xc0001ef180, 0x131, 0x131)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/transport.go:55 +0x64
github.com/hirochachacha/go-smb2.(*conn).runReciever(0xc0004661a0)
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/conn.go:502 +0x13d
created by github.com/hirochachacha/go-smb2.(*Negotiator).negotiate
       /Users/usirsiwal/work/dg/sasource/jupiter/src/golib/src/github.com/hirochachacha/go-smb2/conn.go:99 +0x1b4
 
rax    0x104
rbx    0xb00
rcx    0x7ffeefbff728
rdx    0xb00
rdi    0x46f3188
rsi    0x11510100115200
rbp    0x7ffeefbff7c0
rsp    0x7ffeefbff728
r8     0x0
r9     0xa0
r10    0x0
r11    0x246
r12    0x46f3188
r13    0x16
r14    0x11510100115200
r15    0x115200
rip    0x7fff6dd92ce6
rflags 0x247
cs     0x7
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).

**Comment by hirochachacha** [comment]
It looks like connection error. Does the target server work fine?

**Comment by hirochachacha** [comment]
Or if your program is long running process, you may need to customize keepalive of TCP connection.

**Comment by testcheyi** [comment]
Thanks for looking into this. We resolved the network issue and could not reproduce it any longer.
